name: Build AppImage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        include:
          - arch: x86_64
            runner: [self-hosted, Linux, X64, appimage]
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    env:
      INSTALL_DIR: ${{ github.workspace }}/install

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        if: matrix.arch == 'aarch64'
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: self-hosted-prod
          max-size: 0

      - name: Configure CMake
        run: |
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            nix develop --command cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
          else
            cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
          fi

      - name: Build
        run: |
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            nix develop --command cmake --build build --parallel $(nproc)
          else
            cmake --build build --parallel $(nproc)
          fi

      - name: Install
        run: |
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            nix develop --command cmake --install build
          else
            cmake --install build
          fi

      - name: Make AppImage
        run: |
          chmod +x ./scripts/mkappimage.sh
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
             nix develop --command ./scripts/mkappimage.sh "${INSTALL_DIR}" AppDir
          else
             ./scripts/mkappimage.sh "${INSTALL_DIR}" AppDir
          fi

