name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            compiler_name: GCC
            cc: gcc
            cxx: g++
            runner: ${{ github.repository == 'vicinaehq/vicinae' && '["self-hosted", "Linux", "X64", "prod"]' || '["ubuntu-latest"]' }}
          - arch: x86_64
            compiler_name: Clang
            cc: clang
            cxx: clang++
            runner: ${{ github.repository == 'vicinaehq/vicinae' && '["self-hosted", "Linux", "X64", "prod"]' || '["ubuntu-latest"]' }}
          - arch: aarch64
            compiler_name: GCC
            cc: gcc
            cxx: g++
            runner: '["ubuntu-24.04-arm"]'
    runs-on: ${{ fromJSON(matrix.runner) }}

    name: Build (${{ matrix.arch }}, ${{ matrix.compiler_name }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        if: matrix.arch == 'aarch64'
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Configure CMake
        run: |
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            # We don't pass compilers here, nix develop shellHook sets CC/CXX to gcc15
            nix develop --command cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
          else
            cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DCMAKE_PREFIX_PATH=$Qt6_DIR -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
          fi

      - name: Build
        run: |
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            nix develop --command cmake --build build --parallel $(nproc)
          else
            cmake --build build --parallel $(nproc)
          fi

      - name: Run Tests
        run: |
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            nix develop --command make test
          else
            make test
          fi
